plugin:
    name: 'vdomah.rolesbuddies::lang.plugin.name'
    description: 'vdomah.rolesbuddies::lang.plugin.description'
    author: 'Art Gek'
    icon: oc-icon-cubes
    homepage: 'https://github.com/vdomah/oc-rolesbuddies-plugin'
